apiVersion: apps/v1
kind: Deployment
metadata:
  name: airquality
  labels:
    role: airquality
spec:
  replicas: 1
  selector:
    matchLabels:
      role: airquality
  template:
    metadata:
      labels:
        role: airquality
    spec:
      containers:
        - name: airquality
          image: repository.avsystem.com/docker-local/airquality
          imagePullPolicy: Always
          resources:
            limits:
              memory: "150Mi"
              cpu: "200m"
          env:
            - name: DEVICEID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_ADDRESS
              #value: "xxx"
              value: "xxx"
            - name: OPEN_WEATHER_API_TOKEN
              value: "xxx"
