apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: air-quality-meter-example
  labels:
    role: air-quality-meter-example
spec:
  serviceName: air-quality-meter-example
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      role: air-quality-meter-example
  template:
    metadata:
      labels:
        role: air-quality-meter-example
    spec:
      containers:
        - name: air-quality-meter-example
          image: repository.avsystem.com/docker-local/air-quality-meter-example-psk
          imagePullPolicy: Always
          resources:
            limits:
              memory: "150Mi"
              cpu: "200m"
          env:
            - name: DEVICEID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IDENTITY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KEY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_PORT
              value: "6684"
            - name: SERVER_ADDRESS
              value: "xxx"
            - name: OPEN_WEATHER_API_TOKEN
              value: "xxx"
            - name: SERVER_PROTOCOL
              value: "coaps"
