# This is a basic workflow to help you get started with Actions

name: Update lambdas for cloud formation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the CDM-246
  push:
    branches: [ CDM-246 ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout@v2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::039321617281:role/github-avsystem
          aws-region: eu-central-1

      - name: Go to cloud-formation dir
        run: cd coiote-aws-iot-cloud-formation

      - name: Install lambdas requirements
        run: find . -name requirements.txt -print0 | xargs -0 -n1 dirname | xargs -I '{}' pip install -r {}/requirements.txt --target {}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: find . -name requirements.txt -print0 | xargs -0 -n1 dirname | xargs ls -l

      - name: list files in current folder
        run: ls -l

      - name: Build and upload lambdas
        run: aws cloudformation package --template-file cloudFormation.json --s3-bucket coiote-aws-integration --output-template-file coiote-aws-integration-cf-template.json --use-json

      - name: Upload template to S3
        run: aws s3 sync --exclude="*" --include="*.json" . s3://coiote-aws-integration
